id: I98916018
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T16:54:45+00:00'
last_modified: '2022-06-08T05:51:12.360045+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG4479
  title: བསྟན་སྙིང་ཡིག་ཆ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    EEB5:
      image_group_id: I1KG4515
      title: ''
      total_pages: 836
      order: 1
      base_file: EEB5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
